#!/bin/bash

root_dir="$(dirname $(readlink -f $0))"
fzf_src_dir="${root_dir}/fzf"
out_dir="${root_dir}/config"

XDG_CONFIG_HOME="${out_dir}" "${fzf_src_dir}/install" --xdg --no-zsh --no-fish --no-update-rc --key-bindings --completion

cat <<EOF >>${HOME}/.bashrc

# Generated by fzf-setup (${root_dir}) install script
# -------------------
source ${out_dir}/fzf.sh

EOF